version: '3'
services:
  whatsapp-http-api:
    image: devlikeapro/whatsapp-http-api
    container_name: whatsapp-http-api
    ports:
      - '3000:3000/tcp'
    environment:
      # Environment variables from https://waha.devlike.pro/docs/how-to/config/
      - WHATSAPP_HOOK_URL=https://n8n.op-madrasah.biz.id/webhook/whatsapp-http-api
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    restart: always
    
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017/tcp'
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: {}
